package com.onemonth.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mrgao.onemonth.bean.Classify;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLASSIFY".
*/
public class ClassifyDao extends AbstractDao<Classify, Void> {

    public static final String TABLENAME = "CLASSIFY";

    /**
     * Properties of entity Classify.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Classify = new Property(0, String.class, "classify", false, "CLASSIFY");
    }


    public ClassifyDao(DaoConfig config) {
        super(config);
    }
    
    public ClassifyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLASSIFY\" (" + //
                "\"CLASSIFY\" TEXT);"); // 0: classify
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLASSIFY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Classify entity) {
        stmt.clearBindings();
 
        String classify = entity.getClassify();
        if (classify != null) {
            stmt.bindString(1, classify);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Classify entity) {
        stmt.clearBindings();
 
        String classify = entity.getClassify();
        if (classify != null) {
            stmt.bindString(1, classify);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Classify readEntity(Cursor cursor, int offset) {
        Classify entity = new Classify( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // classify
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Classify entity, int offset) {
        entity.setClassify(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Classify entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Classify entity) {
        return null;
    }

    @Override
    public boolean hasKey(Classify entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
