package com.onemonth.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mrgao.onemonth.bean.JudgeByDay;
import com.mrgao.onemonth.bean.Task;
import com.mrgao.onemonth.bean.TaskGroup;
import com.mrgao.onemonth.bean.JudgeByGroup;

import com.onemonth.dao.JudgeByDayDao;
import com.onemonth.dao.TaskDao;
import com.onemonth.dao.TaskGroupDao;
import com.onemonth.dao.JudgeByGroupDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig judgeByDayDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig taskGroupDaoConfig;
    private final DaoConfig judgeByGroupDaoConfig;

    private final JudgeByDayDao judgeByDayDao;
    private final TaskDao taskDao;
    private final TaskGroupDao taskGroupDao;
    private final JudgeByGroupDao judgeByGroupDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        judgeByDayDaoConfig = daoConfigMap.get(JudgeByDayDao.class).clone();
        judgeByDayDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        taskGroupDaoConfig = daoConfigMap.get(TaskGroupDao.class).clone();
        taskGroupDaoConfig.initIdentityScope(type);

        judgeByGroupDaoConfig = daoConfigMap.get(JudgeByGroupDao.class).clone();
        judgeByGroupDaoConfig.initIdentityScope(type);

        judgeByDayDao = new JudgeByDayDao(judgeByDayDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        taskGroupDao = new TaskGroupDao(taskGroupDaoConfig, this);
        judgeByGroupDao = new JudgeByGroupDao(judgeByGroupDaoConfig, this);

        registerDao(JudgeByDay.class, judgeByDayDao);
        registerDao(Task.class, taskDao);
        registerDao(TaskGroup.class, taskGroupDao);
        registerDao(JudgeByGroup.class, judgeByGroupDao);
    }
    
    public void clear() {
        judgeByDayDaoConfig.clearIdentityScope();
        taskDaoConfig.clearIdentityScope();
        taskGroupDaoConfig.clearIdentityScope();
        judgeByGroupDaoConfig.clearIdentityScope();
    }

    public JudgeByDayDao getJudgeByDayDao() {
        return judgeByDayDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public TaskGroupDao getTaskGroupDao() {
        return taskGroupDao;
    }

    public JudgeByGroupDao getJudgeByGroupDao() {
        return judgeByGroupDao;
    }

}
