package com.onemonth.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mrgao.onemonth.bean.TaskGroup;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK_GROUP".
*/
public class TaskGroupDao extends AbstractDao<TaskGroup, Long> {

    public static final String TABLENAME = "TASK_GROUP";

    /**
     * Properties of entity TaskGroup.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CreateTime = new Property(1, long.class, "createTime", false, "CREATE_TIME");
        public final static Property EndTime = new Property(2, long.class, "endTime", false, "END_TIME");
        public final static Property ChangeTime = new Property(3, long.class, "changeTime", false, "CHANGE_TIME");
        public final static Property CreateTimeS = new Property(4, String.class, "createTimeS", false, "CREATE_TIME_S");
        public final static Property EndTimeS = new Property(5, String.class, "endTimeS", false, "END_TIME_S");
        public final static Property ChangeTimeS = new Property(6, String.class, "changeTimeS", false, "CHANGE_TIME_S");
        public final static Property FinishNum = new Property(7, int.class, "finishNum", false, "FINISH_NUM");
        public final static Property DayNum = new Property(8, int.class, "dayNum", false, "DAY_NUM");
        public final static Property TargetNum = new Property(9, int.class, "targetNum", false, "TARGET_NUM");
        public final static Property Classify = new Property(10, String.class, "classify", false, "CLASSIFY");
        public final static Property Icon = new Property(11, String.class, "icon", false, "ICON");
        public final static Property Color = new Property(12, String.class, "color", false, "COLOR");
        public final static Property Grade = new Property(13, String.class, "grade", false, "GRADE");
        public final static Property Type = new Property(14, String.class, "type", false, "TYPE");
        public final static Property Repeat = new Property(15, String.class, "repeat", false, "REPEAT");
        public final static Property Data = new Property(16, String.class, "data", false, "DATA");
        public final static Property Title = new Property(17, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(18, String.class, "content", false, "CONTENT");
        public final static Property RepeatType = new Property(19, String.class, "repeatType", false, "REPEAT_TYPE");
        public final static Property IsFinish = new Property(20, boolean.class, "isFinish", false, "IS_FINISH");
        public final static Property IsDelay = new Property(21, boolean.class, "isDelay", false, "IS_DELAY");
    }


    public TaskGroupDao(DaoConfig config) {
        super(config);
    }
    
    public TaskGroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK_GROUP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 1: createTime
                "\"END_TIME\" INTEGER NOT NULL ," + // 2: endTime
                "\"CHANGE_TIME\" INTEGER NOT NULL ," + // 3: changeTime
                "\"CREATE_TIME_S\" TEXT," + // 4: createTimeS
                "\"END_TIME_S\" TEXT," + // 5: endTimeS
                "\"CHANGE_TIME_S\" TEXT," + // 6: changeTimeS
                "\"FINISH_NUM\" INTEGER NOT NULL ," + // 7: finishNum
                "\"DAY_NUM\" INTEGER NOT NULL ," + // 8: dayNum
                "\"TARGET_NUM\" INTEGER NOT NULL ," + // 9: targetNum
                "\"CLASSIFY\" TEXT," + // 10: classify
                "\"ICON\" TEXT," + // 11: icon
                "\"COLOR\" TEXT," + // 12: color
                "\"GRADE\" TEXT," + // 13: grade
                "\"TYPE\" TEXT," + // 14: type
                "\"REPEAT\" TEXT," + // 15: repeat
                "\"DATA\" TEXT," + // 16: data
                "\"TITLE\" TEXT," + // 17: title
                "\"CONTENT\" TEXT," + // 18: content
                "\"REPEAT_TYPE\" TEXT," + // 19: repeatType
                "\"IS_FINISH\" INTEGER NOT NULL ," + // 20: isFinish
                "\"IS_DELAY\" INTEGER NOT NULL );"); // 21: isDelay
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK_GROUP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TaskGroup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCreateTime());
        stmt.bindLong(3, entity.getEndTime());
        stmt.bindLong(4, entity.getChangeTime());
 
        String createTimeS = entity.getCreateTimeS();
        if (createTimeS != null) {
            stmt.bindString(5, createTimeS);
        }
 
        String endTimeS = entity.getEndTimeS();
        if (endTimeS != null) {
            stmt.bindString(6, endTimeS);
        }
 
        String changeTimeS = entity.getChangeTimeS();
        if (changeTimeS != null) {
            stmt.bindString(7, changeTimeS);
        }
        stmt.bindLong(8, entity.getFinishNum());
        stmt.bindLong(9, entity.getDayNum());
        stmt.bindLong(10, entity.getTargetNum());
 
        String classify = entity.getClassify();
        if (classify != null) {
            stmt.bindString(11, classify);
        }
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(12, icon);
        }
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(13, color);
        }
 
        String grade = entity.getGrade();
        if (grade != null) {
            stmt.bindString(14, grade);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(15, type);
        }
 
        String repeat = entity.getRepeat();
        if (repeat != null) {
            stmt.bindString(16, repeat);
        }
 
        String data = entity.getData();
        if (data != null) {
            stmt.bindString(17, data);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(18, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(19, content);
        }
 
        String repeatType = entity.getRepeatType();
        if (repeatType != null) {
            stmt.bindString(20, repeatType);
        }
        stmt.bindLong(21, entity.getIsFinish() ? 1L: 0L);
        stmt.bindLong(22, entity.getIsDelay() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TaskGroup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCreateTime());
        stmt.bindLong(3, entity.getEndTime());
        stmt.bindLong(4, entity.getChangeTime());
 
        String createTimeS = entity.getCreateTimeS();
        if (createTimeS != null) {
            stmt.bindString(5, createTimeS);
        }
 
        String endTimeS = entity.getEndTimeS();
        if (endTimeS != null) {
            stmt.bindString(6, endTimeS);
        }
 
        String changeTimeS = entity.getChangeTimeS();
        if (changeTimeS != null) {
            stmt.bindString(7, changeTimeS);
        }
        stmt.bindLong(8, entity.getFinishNum());
        stmt.bindLong(9, entity.getDayNum());
        stmt.bindLong(10, entity.getTargetNum());
 
        String classify = entity.getClassify();
        if (classify != null) {
            stmt.bindString(11, classify);
        }
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(12, icon);
        }
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(13, color);
        }
 
        String grade = entity.getGrade();
        if (grade != null) {
            stmt.bindString(14, grade);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(15, type);
        }
 
        String repeat = entity.getRepeat();
        if (repeat != null) {
            stmt.bindString(16, repeat);
        }
 
        String data = entity.getData();
        if (data != null) {
            stmt.bindString(17, data);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(18, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(19, content);
        }
 
        String repeatType = entity.getRepeatType();
        if (repeatType != null) {
            stmt.bindString(20, repeatType);
        }
        stmt.bindLong(21, entity.getIsFinish() ? 1L: 0L);
        stmt.bindLong(22, entity.getIsDelay() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TaskGroup readEntity(Cursor cursor, int offset) {
        TaskGroup entity = new TaskGroup( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // createTime
            cursor.getLong(offset + 2), // endTime
            cursor.getLong(offset + 3), // changeTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // createTimeS
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // endTimeS
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // changeTimeS
            cursor.getInt(offset + 7), // finishNum
            cursor.getInt(offset + 8), // dayNum
            cursor.getInt(offset + 9), // targetNum
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // classify
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // icon
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // color
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // grade
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // type
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // repeat
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // data
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // title
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // content
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // repeatType
            cursor.getShort(offset + 20) != 0, // isFinish
            cursor.getShort(offset + 21) != 0 // isDelay
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TaskGroup entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCreateTime(cursor.getLong(offset + 1));
        entity.setEndTime(cursor.getLong(offset + 2));
        entity.setChangeTime(cursor.getLong(offset + 3));
        entity.setCreateTimeS(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEndTimeS(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setChangeTimeS(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFinishNum(cursor.getInt(offset + 7));
        entity.setDayNum(cursor.getInt(offset + 8));
        entity.setTargetNum(cursor.getInt(offset + 9));
        entity.setClassify(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setIcon(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setColor(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setGrade(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setType(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setRepeat(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setData(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTitle(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setContent(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setRepeatType(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setIsFinish(cursor.getShort(offset + 20) != 0);
        entity.setIsDelay(cursor.getShort(offset + 21) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TaskGroup entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TaskGroup entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TaskGroup entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
